### ISSUE TITLE
function repositoryExists() failing

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord-box3/translation-helps#6]
https://github.com/unfoldingWord-box3/translation-helps/blob/ae5e76d0f55b2f59ffa5c702cc6cb530498e00e6/src/components/Viewer/gitApi.js#L151

I was debugging why I am unable to access the tA markdown files and found that the above function is not finding the repository `en_ta`. Spitting out the returned repos in the get() function, found that it was returning near matches (not sure how the query is supposed to work). It returned 10 repos which will match the number DCS itself returns. But as can be seen below, two are returned twice. And two are missing.

API search for repos found:
0 name: "en-ta-audio"
1 name: "en-ta-checking-vol1"
2 name: "en-ta-checking-vol2"
3 name: "en-ta-intro"
4 name: "en-ta-intro"
5 name: "en-ta-process"
6 name: "en-ta-process"
7 name: "en-ta-tech-vol1"
8 name: "en-ta-tech-vol2"
9 name: "en-ta-translate-vol1"

Missing: 
en_ta
en-ta-translate-vol2

**Comment by klappy** [comment]
@mandolyte Thanks for reporting this.

According to the documentation, 50 is the limit to the search results. One of two things, or both, have happened since this use to work. The number of results have grown since then, or the server's default limit has changed to 10 where it use to be 50. 

Here is the problematic API call:
https://git.door43.org/api/v1/repos/search?q=en_ta&uid=0

It can be fixed by adding the query parameter `limit=100`.
https://git.door43.org/api/v1/repos/search?q=en_ta&uid=0&limit=100

Here is the fix in this codebase: https://github.com/unfoldingWord-box3/translation-helps/commit/16839debdc7e863489464c39258207c2e67da463#diff-ba70065183f39b0b7d2195f7639327ef
